# Analisis Mitra yang Memiliki Dokumen Kerja Sama

Notebook ini menganalisis mitra (distinct) yang bekerja sama dan memiliki dokumen kerja sama.

**Informasi yang ditampilkan:**
- Nama Mitra
- Nomor Telepon Mitra
- Email Mitra
- Nama Penandatangan Mitra
- PIC Mitra (Person In Charge)
- Nomor Telepon PIC
- Email PIC
- Tanggal Mulai Kerja Sama

## 1. Import Library & Load Data

In [15]:
import pandas as pd
import os

# Path ke folder data
data_dir = 'data'

# Load semua tabel yang dibutuhkan
df_mitra = pd.read_csv(os.path.join(data_dir, 'T_mitra - T_mitra.csv'))
df_person = pd.read_csv(os.path.join(data_dir, 'T_person - T_person.csv'))
df_dokumen = pd.read_csv(os.path.join(data_dir, 'T_dokumen_kerjasama - T_dokumen_kerjasama.csv'))
df_pengajuan = pd.read_csv(os.path.join(data_dir, 'T_pengajuan_kerjasama - T_pengajuan_kerjasama.csv'))
df_mapping_mitra = pd.read_csv(os.path.join(data_dir, 'M_mitra_bekerjasama - M_mitra_bekerjasama.csv'))

print(f'Jumlah Mitra: {len(df_mitra)}')
print(f'Jumlah Person: {len(df_person)}')
print(f'Jumlah Dokumen Kerjasama: {len(df_dokumen)}')
print(f'Jumlah Pengajuan Kerjasama: {len(df_pengajuan)}')
print(f'Jumlah Mapping Mitra Bekerjasama: {len(df_mapping_mitra)}')

Jumlah Mitra: 615
Jumlah Person: 651
Jumlah Dokumen Kerjasama: 844
Jumlah Pengajuan Kerjasama: 883
Jumlah Mapping Mitra Bekerjasama: 969

## 2. Preview Data

In [16]:
print('=== T_mitra (5 baris pertama) ===')
display(df_mitra.head())

print('\n=== M_mitra_bekerjasama (5 baris pertama) ===')
display(df_mapping_mitra.head())

print('\n=== T_dokumen_kerjasama (5 baris pertama) ===')
display(df_dokumen[['id', 'ref_pengajuan_kerjasama', 'tanggal_mulai', 'tanggal_berakhir', 'nomor_dokumen']].head())

print('\n=== T_person (5 baris pertama) ===')
display(df_person.head())

=== T_mitra (5 baris pertama) ===

,id,nib,mitra,kategori_mitra,badan_mitra,kriteria_mitra,klasifikasi_mitra,klbi,tanggal_pendirian,alamat,negara_mitra,provinsi_mitra,kabupaten_kota_mitra,email,telepon,kodepos,website,logo,profil,sub_kategori_mitra
0,3945ddae,NaN,FAKULTAS TEKNIK SIPIL DAN LINGKUNGAN INSTITUT ...,"Perguruan tinggi, fakultas, atau program studi...",NEGERI,"Perguruan Tinggi, Fakultas, Atau Program Studi...",NaN,NaN,NaN,NaN,INDONESIA,Jawa Barat,Bandung,NaN,NaN,NaN,NaN,T_mitra_Images/3945ddae.logo.033432.png,NaN,NaN
1,f52370d0,NaN,UNIVERSITAS BRAWIJAYA,Perguruan tinggi yang masuk dalam daftar QS200...,NEGERI,Perguruan Tinggi Yang Masuk Dalam Daftar QS200...,NaN,NaN,NaN,Jalan Veteran,INDONESIA,Jawa Timur,Malang,NaN,NaN,NaN,NaN,T_mitra_Images/f52370d0.logo.033403.jpg,NaN,NaN
2,1eba2efe,NaN,POLITEKNIK NEGERI BATAM,"Perguruan tinggi, fakultas, atau program studi...",NEGERI,"Perguruan Tinggi, Fakultas, Atau Program Studi...",NaN,NaN,NaN,NaN,INDONESIA,Kepulauan Riau,Kota Batam,NaN,NaN,NaN,NaN,T_mitra_Images/1eba2efe.logo.033517.png,NaN,NaN
3,56250757,NaN,POLITEKNIK PERIKANAN NEGERI TUAL,"Perguruan tinggi, fakultas, atau program studi...",NEGERI,"Perguruan Tinggi, Fakultas, Atau Program Studi...",NaN,NaN,NaN,NaN,INDONESIA,Maluku,Kota Tual,NaN,NaN,NaN,NaN,T_mitra_Images/56250757.logo.033621.png,NaN,NaN
4,6f5770bf,NaN,UNIVERSITAS TANJUNGPURA (UNTAN),Perguruan tinggi yang masuk dalam daftar QS200...,NEGERI,Perguruan Tinggi Yang Masuk Dalam Daftar QS200...,NaN,NaN,NaN,NaN,INDONESIA,Kalimantan Barat,Kota Pontianak,NaN,NaN,NaN,NaN,T_mitra_Images/6f5770bf.logo.033648.png,NaN,NaN

=== M_mitra_bekerjasama (5 baris pertama) ===

,id,ref_pengajuan_kerjasama,ref_mitra,ref_pic_mitra,ref_penandatangan_mitra,nomor_dokumen_mitra,jabatan_pic_mitra,jabatan_penandatangan_mitra
0,8e767a64,0857f568,3945ddae,NaN,NaN,1263/I.1C09/DN/2012,NaN,NaN
1,e611eba2,8f3a6a08,f52370d0,NaN,NaN,42/UN10/DN/2016,NaN,NaN
2,ee70d5dc,908f0bf8,1eba2efe,NaN,NaN,31/MOU.PL29/XII/2014,NaN,NaN
3,99105166,368d8046,56250757,NaN,NaN,07/PL26.R/MOU/XII/2014,NaN,NaN
4,49a17770,98b2d8b1,6f5770bf,NaN,NaN,641/UN22/DN/2014,NaN,NaN

=== T_dokumen_kerjasama (5 baris pertama) ===

,id,ref_pengajuan_kerjasama,tanggal_mulai,tanggal_berakhir,nomor_dokumen
0,c17c22e8,0857f568,07/31/2012,07/30/2017,2438/PL16/KL/2012
1,0fb4e754,8f3a6a08,05/19/2016,05/18/2021,1376/PL16/KB/2016
2,b9a8a616,908f0bf8,11/26/2014,11/25/2019,927/PL16/KB/2014
3,6d2696bc,368d8046,11/26/2014,11/25/2019,926/PL16/KB/2014
4,758d532c,98b2d8b1,03/12/2014,03/11/2019,161/PL16/KB/2014

=== T_person (5 baris pertama) ===

,id,nama,email,telepon,jabatan,alamat,kantor
0,ab3614e4,Dr. Michael Green,mag19@le.ac.uk,+44 116 252 2296,NaN,NaN,NaN
1,70c9ba28,"Sarwono, A.Pi.",pemangkat_ppn@yahoo.com,0562244113,NaN,NaN,NaN
2,e9eaaa34,Humas,humas@polipangkep.ac.id,04102312704,NaN,NaN,NaN
3,4666242e,"Ketua Prodi S1 Teknik Fisika, Fakultas Teknik ...",see.secretariat@telkomuniversity.ac.id,0227566456,NaN,NaN,NaN
4,16b8c6cd,Direktur Excellence English Studio,excellence.englishstudio@gmail.com,17132393989,NaN,NaN,NaN

## 3. Menggabungkan Data

Alur relasi:
1. **M_mitra_bekerjasama** → `ref_mitra` → **T_mitra** (info mitra)
2. **M_mitra_bekerjasama** → `ref_penandatangan_mitra` → **T_person** (penandatangan)
3. **M_mitra_bekerjasama** → `ref_pic_mitra` → **T_person** (PIC mitra)
4. **M_mitra_bekerjasama** → `ref_pengajuan_kerjasama` → **T_dokumen_kerjasama** (tanggal mulai)

In [17]:
# Step 1: Join mapping mitra dengan data mitra
df_merged = df_mapping_mitra.merge(
    df_mitra[['id', 'mitra', 'email', 'telepon']].rename(columns={
        'id': 'id_mitra',
        'mitra': 'nama_mitra',
        'email': 'email_mitra',
        'telepon': 'telepon_mitra'
    }),
    left_on='ref_mitra',
    right_on='id_mitra',
    how='left'
)
df_merged.drop(columns=['id_mitra'], inplace=True, errors='ignore')

print(f'Setelah join mitra: {len(df_merged)} baris')
df_merged[['nama_mitra', 'email_mitra', 'telepon_mitra']].head()

Setelah join mitra: 972 baris

                                          nama_mitra email_mitra telepon_mitra
0  FAKULTAS TEKNIK SIPIL DAN LINGKUNGAN INSTITUT ...         NaN           NaN
1                              UNIVERSITAS BRAWIJAYA         NaN           NaN
2                            POLITEKNIK NEGERI BATAM         NaN           NaN
3                   POLITEKNIK PERIKANAN NEGERI TUAL         NaN           NaN
4                    UNIVERSITAS TANJUNGPURA (UNTAN)         NaN           NaN

In [18]:
# Step 2: Join dengan T_person untuk Penandatangan Mitra
df_merged = df_merged.merge(
    df_person[['id', 'nama', 'email', 'telepon']].rename(columns={
        'id': 'id_penandatangan',
        'nama': 'nama_penandatangan',
        'email': 'email_penandatangan',
        'telepon': 'telepon_penandatangan'
    }),
    left_on='ref_penandatangan_mitra',
    right_on='id_penandatangan',
    how='left'
)
df_merged.drop(columns=['id_penandatangan'], inplace=True, errors='ignore')

print(f'Setelah join penandatangan: {len(df_merged)} baris')
df_merged[['nama_mitra', 'nama_penandatangan']].head()

Setelah join penandatangan: 2917 baris

                                          nama_mitra nama_penandatangan
0  FAKULTAS TEKNIK SIPIL DAN LINGKUNGAN INSTITUT ...                NaN
1  FAKULTAS TEKNIK SIPIL DAN LINGKUNGAN INSTITUT ...                NaN
2  FAKULTAS TEKNIK SIPIL DAN LINGKUNGAN INSTITUT ...                NaN
3  FAKULTAS TEKNIK SIPIL DAN LINGKUNGAN INSTITUT ...                NaN
4  FAKULTAS TEKNIK SIPIL DAN LINGKUNGAN INSTITUT ...                NaN

In [19]:
# Step 3: Join dengan T_person untuk PIC Mitra
df_merged = df_merged.merge(
    df_person[['id', 'nama', 'email', 'telepon']].rename(columns={
        'id': 'id_pic',
        'nama': 'nama_pic_mitra',
        'email': 'email_pic_mitra',
        'telepon': 'telepon_pic_mitra'
    }),
    left_on='ref_pic_mitra',
    right_on='id_pic',
    how='left'
)
df_merged.drop(columns=['id_pic'], inplace=True, errors='ignore')

print(f'Setelah join PIC: {len(df_merged)} baris')
df_merged[['nama_mitra', 'nama_pic_mitra', 'telepon_pic_mitra', 'email_pic_mitra']].head()

Setelah join PIC: 16222 baris

,nama_mitra,nama_pic_mitra,telepon_pic_mitra,email_pic_mitra
0,FAKULTAS TEKNIK SIPIL DAN LINGKUNGAN INSTITUT ...,NaN,NaN,NaN
1,FAKULTAS TEKNIK SIPIL DAN LINGKUNGAN INSTITUT ...,NaN,NaN,NaN
2,FAKULTAS TEKNIK SIPIL DAN LINGKUNGAN INSTITUT ...,NaN,NaN,NaN
3,FAKULTAS TEKNIK SIPIL DAN LINGKUNGAN INSTITUT ...,NaN,NaN,NaN
4,FAKULTAS TEKNIK SIPIL DAN LINGKUNGAN INSTITUT ...,NaN,NaN,NaN

In [20]:
# Step 4: Join dengan T_dokumen_kerjasama untuk mendapatkan tanggal_mulai
# Relasi: M_mitra_bekerjasama.ref_pengajuan_kerjasama == T_dokumen_kerjasama.ref_pengajuan_kerjasama

# Parse tanggal_mulai
df_dokumen['tanggal_mulai_parsed'] = pd.to_datetime(df_dokumen['tanggal_mulai'], format='mixed', errors='coerce')

# Ambil tanggal_mulai paling awal, nomor_dokumen, dan link_dokumen per pengajuan
df_dok_agg = df_dokumen.groupby('ref_pengajuan_kerjasama').agg(
    tanggal_mulai=('tanggal_mulai_parsed', 'min'),
    nomor_dokumen=('nomor_dokumen', 'first'),
    link_dokumen=('link_dokumen', 'first')
).reset_index()

df_merged = df_merged.merge(
    df_dok_agg,
    left_on='ref_pengajuan_kerjasama',
    right_on='ref_pengajuan_kerjasama',
    how='inner'  # INNER join: hanya mitra yang memiliki dokumen kerjasama
)

print(f'Setelah join dokumen (hanya mitra dengan dokumen): {len(df_merged)} baris')
df_merged[['nama_mitra', 'tanggal_mulai', 'nomor_dokumen', 'link_dokumen']].head()

Setelah join dokumen (hanya mitra dengan dokumen): 15312 baris

,nama_mitra,tanggal_mulai,nomor_dokumen,link_dokumen
0,FAKULTAS TEKNIK SIPIL DAN LINGKUNGAN INSTITUT ...,2012-07-31,2438/PL16/KL/2012,https://drive.google.com/file/d/1dfnzePs7wErXD...
1,FAKULTAS TEKNIK SIPIL DAN LINGKUNGAN INSTITUT ...,2012-07-31,2438/PL16/KL/2012,https://drive.google.com/file/d/1dfnzePs7wErXD...
2,FAKULTAS TEKNIK SIPIL DAN LINGKUNGAN INSTITUT ...,2012-07-31,2438/PL16/KL/2012,https://drive.google.com/file/d/1dfnzePs7wErXD...
3,FAKULTAS TEKNIK SIPIL DAN LINGKUNGAN INSTITUT ...,2012-07-31,2438/PL16/KL/2012,https://drive.google.com/file/d/1dfnzePs7wErXD...
4,FAKULTAS TEKNIK SIPIL DAN LINGKUNGAN INSTITUT ...,2012-07-31,2438/PL16/KL/2012,https://drive.google.com/file/d/1dfnzePs7wErXD...

## 4. Distinct Mitra & Hasil Akhir

Menampilkan mitra yang **distinct** (tidak duplikat) beserta informasi yang diminta.

In [21]:
# Pilih kolom yang dibutuhkan
kolom_hasil = [
    'nama_mitra',
    'telepon_mitra',
    'email_mitra',
    'nama_penandatangan',
    'nama_pic_mitra',
    'telepon_pic_mitra',
    'email_pic_mitra',
    'tanggal_mulai',
    'nomor_dokumen',
    'link_dokumen'
]

df_hasil = df_merged[kolom_hasil].copy()

# Distinct berdasarkan nama_mitra (drop duplicates)
df_distinct = df_hasil.drop_duplicates(subset=['nama_mitra'], keep='first')
df_distinct = df_distinct.sort_values('nama_mitra').reset_index(drop=True)

# Tambahkan kolom semester berdasarkan tanggal_mulai
def tentukan_semester(tgl):
    if pd.isna(tgl):
        return None
    if pd.Timestamp('2023-07-01') <= tgl <= pd.Timestamp('2024-06-30'):
        return 'Semester 2023/2024'
    elif pd.Timestamp('2024-07-01') <= tgl <= pd.Timestamp('2025-06-30'):
        return 'Semester 2024/2025'
    elif pd.Timestamp('2025-07-01') <= tgl <= pd.Timestamp('2026-06-30'):
        return 'Semester 2025/2026'
    else:
        return None

df_distinct['semester'] = df_distinct['tanggal_mulai'].apply(tentukan_semester)

# Hapus data yang tidak termasuk dalam semester manapun
df_distinct = df_distinct.dropna(subset=['semester'])

# Urutkan berdasarkan semester lalu nama mitra
df_distinct = df_distinct.sort_values(['semester', 'nama_mitra']).reset_index(drop=True)
df_distinct.index = df_distinct.index + 1  # Mulai index dari 1
df_distinct.index.name = 'No'

# Format tanggal
df_distinct['tanggal_mulai'] = df_distinct['tanggal_mulai'].dt.strftime('%Y-%m-%d')

print(f'📊 Total Mitra Distinct yang Memiliki Dokumen Kerja Sama: {len(df_distinct)}')
print(f'\nJumlah per Semester:')
print(df_distinct['semester'].value_counts().to_string())
print('=' * 80)
df_distinct

📊 Total Mitra Distinct yang Memiliki Dokumen Kerja Sama: 219

Jumlah per Semester:
semester
Semester 2023/2024    106
Semester 2024/2025     76
Semester 2025/2026     37
================================================================================

,nama_mitra,telepon_mitra,email_mitra,nama_penandatangan,nama_pic_mitra,telepon_pic_mitra,email_pic_mitra,tanggal_mulai,nomor_dokumen,link_dokumen,semester
No,,,,,,,,,,,
1,AKADEMI KOMUNITAS NEGERI ACEH BARAT,NaN,NaN,NaN,NaN,NaN,NaN,2023-12-08,296/PL16/KS.BIV/2023,https://drive.google.com/file/d/1xaAWRt3CMv-YA...,Semester 2023/2024
2,AKADEMI KOMUNITAS NEGERI PACITAN,NaN,NaN,NaN,NaN,NaN,NaN,2023-12-08,296/PL16/KS.BIV/2023,https://drive.google.com/file/d/1xaAWRt3CMv-YA...,Semester 2023/2024
3,AKADEMI KOMUNITAS NEGERI PUTRA SANG FAJAR BLITAR,NaN,NaN,NaN,NaN,NaN,NaN,2023-12-08,296/PL16/KS.BIV/2023,https://drive.google.com/file/d/1xaAWRt3CMv-YA...,Semester 2023/2024
4,AKADEMI KOMUNITAS NEGERI REJANG LEBONG,NaN,NaN,NaN,NaN,NaN,NaN,2023-12-08,296/PL16/KS.BIV/2023,https://drive.google.com/file/d/1xaAWRt3CMv-YA...,Semester 2023/2024
5,AKADEMI KOMUNITAS NEGERI SENI DAN BUDAYA YOGYA...,NaN,NaN,NaN,NaN,NaN,NaN,2023-12-08,296/PL16/KS.BIV/2023,https://drive.google.com/file/d/1xaAWRt3CMv-YA...,Semester 2023/2024
...,...,...,...,...,...,...,...,...,...,...,...
215,UNIVERSITAS ISLAM NEGERI KIAI HAJI ACHMAD SIDD...,085236865802,layanankerjasama@uinkhas.ac.id,"Prof. Dr. H. Hepni, S.Ag., M.M.","As'ari, M.Pd.I",085236865802,layanankerjasama@uinkhas.ac.id,2025-09-12,14812/PL16/KS.00.00/2025,https://drive.google.com/file/d/1wNupQgUImV9C9...,Semester 2025/2026
216,WUHAN CENTRAL FOREIGN ECONOMIC & TECHNICAL COO...,027-82850288,info@whzbdw.com,Xiong Fan,Joury,+62 818-0860-3153,NaN,2025-12-08,7815/PL16/KS.00.00/2025,https://drive.google.com/file/d/1Cx-_uvRTGV0uW...,Semester 2025/2026
217,YAYASAN DZAL HAJRA KUBU RAYA,081345309047,abuyakhmzulkifli@gmail.com,"Zulkifli al Hajra, S.Pd.I., M.Si.","Zulkifli al Hajra, S.Pd.I., M.Si.",081345309047,abuyakhmzulkifli@gmail.com,2025-11-04,3794/PL16/KS.00.00/2025,https://drive.google.com/file/d/1PvjyyZ3jah1jm...,Semester 2025/2026
218,YAYASAN GHALIH PELOPOR PENDIDIKAN,08125156396,info@gpp.or.id,"Muhammad Ghalih, S.I.Kom., M.Sc,. CTM","Muhammad Ghalih, S.I.Kom., M.Sc,. CTM",NaN,NaN,2025-10-06,5554/PL16/KS.00.00/2025,https://drive.google.com/file/d/1cIPFnhoPMBVlp...,Semester 2025/2026
219,YAYASAN PERGURUAN ISLAMIYAH,08115752128,yayasan@islamiyah.id,"Fenni Supriadi, S.E., M.M.","Fenni Supriadi, S.E., M.M.",08115752128,NaN,2025-12-08,5444/PL16/KS.00.00/2025,https://drive.google.com/file/d/1IWBUqAz2fS_Pp...,Semester 2025/2026

## 5. Ringkasan Statistik

In [ ]:
print('📈 RINGKASAN STATISTIK')
print('=' * 50)
print(f'Total mitra unik dengan dokumen kerjasama : {len(df_distinct)}')
print(f'Mitra dengan email terisi                 : {df_distinct["email_mitra"].notna().sum()}')
print(f'Mitra dengan telepon terisi                : {df_distinct["telepon_mitra"].notna().sum()}')
print(f'Mitra dengan penandatangan terisi          : {df_distinct["nama_penandatangan"].notna().sum()}')
print(f'Mitra dengan PIC terisi                    : {df_distinct["nama_pic_mitra"].notna().sum()}')
print(f'PIC dengan telepon terisi                  : {df_distinct["telepon_pic_mitra"].notna().sum()}')
print(f'PIC dengan email terisi                    : {df_distinct["email_pic_mitra"].notna().sum()}')

📈 RINGKASAN STATISTIK
==================================================
Total mitra unik dengan dokumen kerjasama : 219
Mitra dengan email terisi                 : 49
Mitra dengan telepon terisi                : 53
Mitra dengan penandatangan terisi          : 189
Mitra dengan PIC terisi                    : 98
PIC dengan telepon terisi                  : 53
PIC dengan email terisi                    : 53

## 6. Export ke Excel (Opsional)

In [22]:
# Uncomment baris di bawah untuk export ke Excel
output_file = 'hasil_analisis_mitra_distinct.xlsx'
df_distinct.to_excel(output_file, index=True)
print(f'✅ Data berhasil diekspor ke: {output_file}')

✅ Data berhasil diekspor ke: hasil_analisis_mitra_distinct.xlsx